# Generated by Django 4.1 on 2022-08-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('cab_id', models.AutoField(primary_key=True, serialize=False)),
                ('cab_num', models.CharField(max_length=30, unique=True, verbose_name='Номер/Название кабинета')),
                ('cab_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Кабинет',
                'verbose_name_plural': 'Кабинеты',
                'db_table': 'cabinets',
                'ordering': ['cab_num'],
            },
        ),
        migrations.CreateModel(
            name='ComputersIsod',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_reg_num', models.CharField(help_text='Данный номер наклен на системный блок ПК сети ИСОД', max_length=10, unique=True, verbose_name='Рег. номер')),
                ('comp_mac_address', models.CharField(max_length=100, verbose_name='МАС адрес сетевой карты')),
                ('comp_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP-адрес')),
                ('comp_virt_ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Виртуальный IP-адрес')),
                ('comp_id_dst_file', models.CharField(blank=True, max_length=100, verbose_name='ID DST')),
                ('comp_title_dst_file', models.CharField(blank=True, max_length=100, verbose_name='Имя DST')),
                ('comp_attestation_status', models.CharField(choices=[('Присоединен', 'Присоединен'), ('Требует присоединения', 'Требует присоединения')], max_length=100, verbose_name='Состояние аттестации')),
                ('comp_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Компьютер сети ИСОД',
                'verbose_name_plural': 'Компьютеры сети ИСОД',
                'db_table': 'computers_isod',
            },
        ),
        migrations.CreateModel(
            name='DepartmentsFirst',
            fields=[
                ('dep_first_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_first_title', models.CharField(max_length=150, unique=True, verbose_name='Название отдела')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'departments_first',
                'ordering': ['dep_first_title', 'fk_div'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentsRegionalLevel',
            fields=[
                ('drl_id', models.AutoField(primary_key=True, serialize=False)),
                ('drl_title', models.CharField(max_length=250, unique=True, verbose_name='Название ОВД')),
                ('drl_title_area', models.CharField(max_length=100, unique=True, verbose_name='Название района')),
                ('drl_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_self_subordinate', models.ForeignKey(blank=True, db_column='fk_self_subordinate', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.departmentsregionallevel', verbose_name='Входит в состав ОВД')),
            ],
            options={
                'verbose_name': 'Территориальный ОВД на районном уровне',
                'verbose_name_plural': 'Территориальные ОВД на районном уровне',
                'db_table': 'departments_regional_level',
                'ordering': ['drl_title_area'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentsSecond',
            fields=[
                ('dep_second_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_second_title', models.CharField(max_length=150, unique=True, verbose_name='Название отделения')),
                ('fk_dep_first', models.ForeignKey(blank=True, db_column='fk_dep_first', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.departmentsfirst', verbose_name='Отдел')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'db_table': 'departments_second',
                'ordering': ['dep_second_title', 'fk_dep_first'],
            },
        ),
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('div_id', models.AutoField(primary_key=True, serialize=False)),
                ('div_title', models.CharField(max_length=100, unique=True, verbose_name='Название подразделения')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'db_table': 'divisions',
                'ordering': ['div_title'],
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('emp_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('emp_middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('emp_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('emp_gender', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=5, verbose_name='Пол')),
                ('emp_family_status', models.CharField(blank=True, choices=[('Замужем / Женат', 'Замужем / Женат'), ('Не замужем / Не женат', 'Не замужем / Не женат')], max_length=50, verbose_name='Семейное положение')),
                ('emp_date_start_work', models.PositiveIntegerField(blank=True, null=True, verbose_name='С какого года в ОВД')),
                ('emp_date_start_work_ic', models.DateField(blank=True, help_text='Если поступление вновь, то ставится последняя дата', null=True, verbose_name='Дата поступления на службу в ИЦ')),
                ('emp_date_start_position', models.DateField(blank=True, null=True, verbose_name='Дата назначения на текущую должность')),
                ('emp_phone', models.CharField(blank=True, help_text='Формат: 11-11', max_length=50, verbose_name='Сл. тел')),
                ('emp_phone_home', models.CharField(blank=True, help_text='Формат: 11-11-11', max_length=50, verbose_name='Дом. тел.')),
                ('emp_phone_mobile', models.CharField(blank=True, help_text='Формат: 1-111-111-11-11', max_length=100, verbose_name='Моб. тел.')),
                ('emp_home_address', models.CharField(blank=True, help_text='Формат: с указанием города (г. Брянск, ул. ...)', max_length=250, verbose_name='Адрес проживания')),
                ('emp_home_address_reg', models.CharField(blank=True, help_text='Формат: с указанием города (г. Брянск, ул. ...)', max_length=250, verbose_name='Адрес регистрации')),
                ('emp_date_driving_experience', models.PositiveIntegerField(blank=True, help_text='С какого года', null=True, verbose_name='Стаж вождения')),
                ('emp_driving_license_category', models.CharField(blank=True, help_text='Например, B или A, B1', max_length=15, null=True, verbose_name='Категория водительского удостоверения')),
                ('emp_sport_class', models.CharField(blank=True, choices=[('Мастер', 'Мастер'), ('Специалист 1 класса', 'Специалист 1 класса'), ('Специалист 2 класса', 'Специалист 2 класса'), ('Специалист 3 класса', 'Специалист 3 класса')], max_length=50, verbose_name='Квалификационное звание')),
                ('emp_date_sport_class', models.DateField(blank=True, null=True, verbose_name='Дата присвоения квал. звания')),
                ('emp_date_document_sport_class', models.DateField(blank=True, null=True, verbose_name='Дата приказа о присвоении квал. звания')),
                ('emp_number_sport_class', models.CharField(blank=True, help_text='Символ "№" не вносить', max_length=100, verbose_name='№ приказа о присвоении квал. звания')),
                ('emp_date_quali_upgrade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год последнего повышения квалификации')),
                ('emp_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('emp_url', models.SlugField(help_text='Указать анг. буквами ссылку на сотрудника (например: ivanov)', max_length=130, unique=True)),
                ('emp_date_end_work', models.DateField(blank=True, null=True, verbose_name='Дата увольнения (перевода)')),
                ('fk_cabinet_location', models.ForeignKey(blank=True, db_column='fk_cabinet_location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.cabinets', verbose_name='Каб.')),
                ('fk_depart_region_lvl', models.ForeignKey(blank=True, db_column='fk_depart_region_lvl', help_text='Район проживания (соотносится с адресом проживания)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.departmentsregionallevel', verbose_name='Район проживания')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employees',
                'ordering': ['emp_surname', 'emp_name', 'emp_middle_name', 'fk_position__fk_dep_first'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesStatus',
            fields=[
                ('emp_st_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_status', models.CharField(max_length=100, unique=True, verbose_name='Статус сотрудника')),
            ],
            options={
                'verbose_name': 'Статус сотрудника',
                'verbose_name_plural': 'Статусы сотрудников',
                'db_table': 'employees_status',
                'ordering': ['emp_status'],
            },
        ),
        migrations.CreateModel(
            name='PropertyStandarts',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('ps_name', models.CharField(max_length=250, unique=True, verbose_name='Наименование имущества')),
                ('ps_type', models.CharField(blank=True, choices=[('Средства связи', 'Средства связи'), ('Средства вычислительной техники', 'Средства вычислительной техники'), ('Средства электронной организационной техники', 'Средства электронной организационной техники'), ('Специальная техника', 'Специальная техника')], max_length=50, verbose_name='Тип имущества')),
                ('ps_quantity_limit', models.IntegerField(blank=True, null=True, verbose_name='Количество положенного имущества')),
                ('ps_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Норма положенности',
                'verbose_name_plural': 'Нормы положенности',
                'db_table': 'property_standarts',
                'ordering': ['ps_name', 'ps_type'],
            },
        ),
        migrations.CreateModel(
            name='Ranks',
            fields=[
                ('r_id', models.AutoField(primary_key=True, serialize=False)),
                ('r_title', models.CharField(max_length=250, unique=True, verbose_name='Звание')),
                ('r_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Звание',
                'verbose_name_plural': 'Звания',
                'db_table': 'ranks',
                'ordering': ['r_title'],
            },
        ),
        migrations.CreateModel(
            name='TypesProperty',
            fields=[
                ('tp_id', models.AutoField(primary_key=True, serialize=False)),
                ('tp_type', models.CharField(max_length=100, unique=True, verbose_name='Вид имущества')),
                ('tp_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Вид имущества',
                'verbose_name_plural': 'Виды имущества',
                'db_table': 'types_property',
                'ordering': ['tp_type'],
            },
        ),
        migrations.CreateModel(
            name='TypesWork',
            fields=[
                ('tw_id', models.AutoField(primary_key=True, serialize=False)),
                ('tw_title', models.CharField(max_length=100, unique=True, verbose_name='Вид службы')),
            ],
            options={
                'verbose_name': 'Вид службы',
                'verbose_name_plural': 'Виды служб',
                'db_table': 'types_work',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('prop_id', models.AutoField(primary_key=True, serialize=False)),
                ('prop_name', models.CharField(blank=True, max_length=250, verbose_name='Наименование имущества')),
                ('prop_ic_num', models.CharField(blank=True, max_length=50, verbose_name='Номер учета ИЦ')),
                ('prop_inventory_num', models.CharField(blank=True, max_length=250, verbose_name='Номер учета УМВД (инв. номер)')),
                ('prop_factory_num', models.CharField(blank=True, max_length=250, verbose_name='Заводской/серийный номер')),
                ('prop_unit_measure', models.CharField(blank=True, choices=[('Комплект', 'Комплект'), ('Штука', 'Штука')], max_length=50, verbose_name='Единица измерения')),
                ('prop_date_delivery', models.DateField(blank=True, null=True, verbose_name='Дата поставки')),
                ('prop_date_exploitation', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('prop_status', models.CharField(choices=[('Исправно', 'Исправно'), ('Неисправно', 'Неисправно'), ('В процессе списания', 'В процессе списания'), ('Списано', 'Списано')], max_length=100, verbose_name='Состояние имущества')),
                ('prop_date_deregistration', models.DateField(blank=True, null=True, verbose_name='Дата списания')),
                ('prop_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_cabinet_location', models.ForeignKey(blank=True, db_column='fk_cabinet_location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.cabinets', verbose_name='Кабинет')),
                ('fk_prop_owner', models.ForeignKey(blank=True, db_column='fk_prop_owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employees', verbose_name='Владелец имущества')),
                ('fk_ps', models.ForeignKey(blank=True, db_column='fk_ps', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.propertystandarts', verbose_name='Вид имущества по нормам положенности')),
                ('fk_tp', models.ForeignKey(blank=True, db_column='fk_tp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.typesproperty', verbose_name='Вид имущества внутренний')),
            ],
            options={
                'verbose_name': 'Имущество',
                'verbose_name_plural': 'Имущество',
                'db_table': 'property',
                'ordering': ['fk_tp', 'prop_name', 'fk_prop_owner'],
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('pos_id', models.AutoField(primary_key=True, serialize=False)),
                ('pos_title', models.CharField(max_length=100, verbose_name='Название должности')),
                ('pos_title_full', models.TextField(blank=True, help_text='н-р: Начальник отделения администрирования баз данных и технологического обслуживания вычислительного центра', verbose_name='Полное название должности')),
                ('pos_quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во должностей по ШР')),
                ('fk_dep_first', models.ForeignKey(blank=True, db_column='fk_dep_first', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.departmentsfirst', verbose_name='Отдел')),
                ('fk_dep_second', models.ForeignKey(blank=True, db_column='fk_dep_second', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.departmentssecond', verbose_name='Отделение')),
                ('fk_division', models.ForeignKey(blank=True, db_column='fk_division', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.divisions', verbose_name='Подразделение')),
                ('fk_types_work', models.ForeignKey(blank=True, db_column='fk_types_work', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.typeswork', verbose_name='Вид службы')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'db_table': 'positions',
                'ordering': ['-fk_dep_first', 'fk_dep_second', 'pos_title'],
            },
        ),
        migrations.CreateModel(
            name='OtherNetworkProperty',
            fields=[
                ('onp_id', models.AutoField(primary_key=True, serialize=False)),
                ('onp_network_type', models.CharField(blank=True, choices=[('Локальная (не ИСОД)', 'Локальная (не ИСОД)'), ('Интернет', 'Интернет')], max_length=100, verbose_name='Вид сети')),
                ('onp_ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='IP-адрес')),
                ('onp_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_prop', models.ForeignKey(blank=True, db_column='fk_prop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.property', verbose_name='Имущество')),
            ],
            options={
                'verbose_name': 'Иное имущество, подключенное к сети',
                'verbose_name_plural': 'Иное имущество, подключенное к сети',
                'db_table': 'other_network_property',
            },
        ),
        migrations.CreateModel(
            name='OtherInformationAboutComputers',
            fields=[
                ('oiac_id', models.AutoField(primary_key=True, serialize=False)),
                ('oiac_os', models.CharField(blank=True, max_length=250, verbose_name='Операционная система')),
                ('oiac_user_name', models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя')),
                ('oiac_user_pass', models.CharField(blank=True, max_length=50, verbose_name='Пароль пользователя')),
                ('oiac_comp_name', models.CharField(blank=True, max_length=50, verbose_name='Имя компьютера')),
                ('oiac_comp_workgroup', models.CharField(blank=True, max_length=50, verbose_name='Рабочая группа компьютера')),
                ('oiac_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_prop', models.ForeignKey(blank=True, db_column='fk_prop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.property', verbose_name='Имущество')),
            ],
            options={
                'verbose_name': 'Иная информация о вычислительной технике',
                'verbose_name_plural': 'Иная информация о вычислительной технике',
                'db_table': 'other_information_about_computers',
            },
        ),
        migrations.CreateModel(
            name='IssueOfficeProducts',
            fields=[
                ('iop_id', models.AutoField(primary_key=True, serialize=False)),
                ('iop_title', models.CharField(blank=True, max_length=100, verbose_name='Название имущества')),
                ('iop_quantity', models.IntegerField(blank=True, null=True, verbose_name='Кол-во выданного')),
                ('iop_date_issue', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('iop_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_op_owner', models.ForeignKey(blank=True, db_column='fk_op_owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employees', verbose_name='Владелец')),
                ('fk_tp', models.ForeignKey(blank=True, db_column='fk_tp', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.typesproperty', verbose_name='Вид имущества внутренний')),
            ],
            options={
                'verbose_name': 'Выдача канц. товара',
                'verbose_name_plural': 'Выдача канц. товаров',
                'db_table': 'issue_office_products',
                'ordering': ['iop_title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesWeapons',
            fields=[
                ('empw_id', models.AutoField(primary_key=True, serialize=False)),
                ('empw_model', models.CharField(max_length=250, verbose_name='Модель оружия')),
                ('empw_caliber', models.CharField(help_text='Например, 12х76', max_length=20, verbose_name='Калибр оружия')),
                ('empw_serial_number', models.CharField(max_length=250, verbose_name='Серия, номер')),
                ('empw_weapon_permit', models.CharField(help_text='Например, РОХа', max_length=250, verbose_name='Название разрешения на оружие')),
                ('empw_weapon_permit_serial_number', models.CharField(max_length=250, unique=True, verbose_name='Серийный номер разрешения')),
                ('empw_start_weapon_permit', models.DateField(verbose_name='Разрешение выдано с')),
                ('empw_end_weapon_permit', models.DateField(verbose_name='Разрешение действительно до')),
                ('empw_type_permit', models.CharField(choices=[('Хранение', 'Хранение'), ('Хранение и ношение', 'Хранение и ношение')], max_length=100, verbose_name='Тип разрешения')),
                ('empw_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_weapon_owner', models.ForeignKey(blank=True, db_column='fk_auto_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic.employees', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сотрудник: личное оружие',
                'verbose_name_plural': 'Сотрудники: личное оружие',
                'db_table': 'employees_weapons',
                'ordering': ['fk_weapon_owner__emp_surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesSpouse',
            fields=[
                ('emps_id', models.AutoField(primary_key=True, serialize=False)),
                ('emps_surname', models.CharField(max_length=50, verbose_name='Фамилия супруга(и)')),
                ('emps_name', models.CharField(max_length=50, verbose_name='Имя супруга(и)')),
                ('emps_middle_name', models.CharField(max_length=50, verbose_name='Отчество супруга(и)')),
                ('emps_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения супруга(и)')),
                ('fk_emp', models.ForeignKey(blank=True, db_column='fk_emp', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic.employees', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник: супруги',
                'verbose_name_plural': 'Сотрудники: супруги',
                'db_table': 'employees_spouse',
                'ordering': ['fk_emp__emp_surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesChildren',
            fields=[
                ('empc_id', models.AutoField(primary_key=True, serialize=False)),
                ('empc_surname', models.CharField(max_length=50, verbose_name='Фамилия ребенка')),
                ('empc_name', models.CharField(max_length=50, verbose_name='Имя ребенка')),
                ('empc_middle_name', models.CharField(max_length=50, verbose_name='Отчество ребенка')),
                ('empc_birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения ребенка')),
                ('empc_gender', models.CharField(blank=True, choices=[('М', 'М'), ('Ж', 'Ж')], max_length=5, verbose_name='Пол ребенка')),
                ('fk_emp', models.ForeignKey(blank=True, db_column='fk_emp', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic.employees', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Сотрудник: дети',
                'verbose_name_plural': 'Сотрудники: дети',
                'db_table': 'employees_children',
                'ordering': ['fk_emp__emp_surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeesAutomoto',
            fields=[
                ('empa_id', models.AutoField(primary_key=True, serialize=False)),
                ('empa_model', models.CharField(max_length=250, verbose_name='Марка авто')),
                ('empa_reg_num', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный знак')),
                ('empa_owner_type', models.CharField(choices=[('В собственности', 'В собственности'), ('В пользовании', 'В пользовании')], max_length=100, verbose_name='Форма собственности')),
                ('empa_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_auto_owner', models.ForeignKey(blank=True, db_column='fk_auto_owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='ic.employees', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Сотрудник: личный автомототранспорт',
                'verbose_name_plural': 'Сотрудники: личный автомототранспорт',
                'db_table': 'employees_automoto',
                'ordering': ['fk_auto_owner__emp_surname'],
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='fk_emp_status',
            field=models.ForeignKey(db_column='fk_emp_status', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employeesstatus', verbose_name='Статус сотрудника'),
        ),
        migrations.AddField(
            model_name='employees',
            name='fk_position',
            field=models.ForeignKey(blank=True, db_column='fk_position', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.positions', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employees',
            name='fk_rank',
            field=models.ForeignKey(blank=True, db_column='fk_rank', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.ranks', verbose_name='Звание, чин, категория'),
        ),
        migrations.CreateModel(
            name='DiskStorageIsod',
            fields=[
                ('disk_id', models.AutoField(primary_key=True, serialize=False)),
                ('disk_reg_num', models.CharField(max_length=10, unique=True, verbose_name='Регистрационный номер')),
                ('disk_model', models.CharField(max_length=100, verbose_name='Модель диска')),
                ('disk_size', models.CharField(help_text='Например, 10 GB, 1 TB (между пробел)', max_length=100, verbose_name='Объем диска')),
                ('disk_factory_num', models.CharField(max_length=100, verbose_name='Заводской номер диска')),
                ('disk_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_disk_owner', models.ForeignKey(blank=True, db_column='fk_disk_owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employees', verbose_name='Владелец')),
                ('fk_install_in_comp', models.ForeignKey(blank=True, db_column='fk_install_in_comp', help_text='Номер компьютера в таблице "Компьютеры в сети ИСОД"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.computersisod', verbose_name='Установлен в компьютер')),
            ],
            options={
                'verbose_name': 'Дисковое хранилище',
                'verbose_name_plural': 'Дисковые хранилища',
                'db_table': 'disk_storage_isod',
                'ordering': ['fk_install_in_comp'],
            },
        ),
        migrations.AddField(
            model_name='departmentsfirst',
            name='fk_div',
            field=models.ForeignKey(blank=True, db_column='fk_div', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.divisions', verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='computersisod',
            name='fk_prop',
            field=models.ForeignKey(blank=True, db_column='fk_prop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.property', verbose_name='Имущество'),
        ),
        migrations.CreateModel(
            name='AccountingCryptographicSecurity',
            fields=[
                ('acs_id', models.AutoField(primary_key=True, serialize=False)),
                ('acs_purpose', models.CharField(blank=True, choices=[('(Должн. лицо) подпись СЭД', '(Должн. лицо) подпись СЭД'), ('(Юр. лицо) подтверждение личности на интернет порт. "Гос. услуг"', '(Юр. лицо) подтверждение личности на интернет порт. "Гос. услуг"'), ('Администратор ГС ПВДНП', 'Администратор ГС ПВДНП'), ('Пользователь ГС ПВДНП', 'Пользователь ГС ПВДНП'), ('Пользователь ГАС ПС', 'Пользователь ГАС ПС')], max_length=100, verbose_name='Предназначение')),
                ('acs_received_organization', models.CharField(blank=True, help_text='Например, ЦИТСиЗИ, ГИАЦ или ИЦ', max_length=100, verbose_name='От кого получено')),
                ('acs_start_date', models.DateField(blank=True, null=True, verbose_name='Начало срока действия')),
                ('acs_final_date', models.DateField(blank=True, null=True, verbose_name='Окончание срока действия')),
                ('acs_status', models.CharField(blank=True, choices=[('Выдано', 'Выдано'), ('Изъято', 'Изъято')], max_length=50, verbose_name='Статус')),
                ('acs_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_prop', models.ForeignKey(blank=True, db_column='fk_prop', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.property', verbose_name='Имущество')),
            ],
            options={
                'verbose_name': 'СКЗИ',
                'verbose_name_plural': 'СКЗИ',
                'db_table': 'accounting_cryptographic_security',
            },
        ),
    ]
