# Generated by Django 4.1 on 2022-11-01 11:37

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeKeepingDoc',
            fields=[
                ('tkd_id', models.AutoField(primary_key=True, serialize=False)),
                ('tkd_doc_reg_num', models.CharField(blank=True, max_length=15, null=True, verbose_name='Рег. номер приказа')),
                ('tkd_date', models.DateField(blank=True, null=True, verbose_name='Дата приказа')),
                ('tkd_doc_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название приказа')),
                ('tkd_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/ic/timekeepingdoc'), upload_to='')),
                ('tkd_note', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Учет времени переработки: Приказ',
                'verbose_name_plural': 'Учет времени переработки: Приказы',
                'db_table': 'time_keeping_doc',
                'ordering': ['tkd_date'],
            },
        ),
        migrations.CreateModel(
            name='TimeKeeping',
            fields=[
                ('tk_id', models.AutoField(primary_key=True, serialize=False)),
                ('tk_quantity_hours_all', models.PositiveSmallIntegerField(verbose_name='Количество часов переработки')),
                ('tk_quantity_hours_received', models.PositiveSmallIntegerField(verbose_name='Количество часов отгулено')),
                ('tk_quantity_hours_received_note', models.TextField(blank=True, verbose_name='Примечание к отгуленным часам')),
                ('tk_quantity_hours_paid', models.PositiveSmallIntegerField(verbose_name='Количество часов оплачено')),
                ('tk_quantity_hours_paid_note', models.TextField(blank=True, verbose_name='Примечание к оплаченным часам')),
                ('tk_note', models.TextField(blank=True, verbose_name='Примечание')),
                ('fk_doc_reg_num', models.ForeignKey(blank=True, db_column='fk_doc_reg_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.timekeepingdoc', verbose_name='ФИО')),
                ('fk_emp_name', models.ForeignKey(blank=True, db_column='fk_emp_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employees', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Учет времени переработки',
                'verbose_name_plural': 'Учет времени переработки',
                'db_table': 'time_keeping',
                'ordering': ['fk_emp_name'],
            },
        ),
    ]
