# Generated by Django 4.1 on 2022-11-01 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0002_timekeepingdoc_timekeeping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeepingdoc',
            name='tkd_file',
            field=models.FileField(blank=True, upload_to='ic/timekeepingdoc'),
        ),
    ]
