# Generated by Django 4.1 on 2022-11-01 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0003_alter_timekeepingdoc_tkd_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='fk_doc_reg_num',
            field=models.ForeignKey(blank=True, db_column='fk_doc_reg_num', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.timekeepingdoc', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='timekeepingdoc',
            name='tkd_file',
            field=models.FileField(blank=True, upload_to='ic/timekeepingdoc', verbose_name='Загрузить файл приказа'),
        ),
    ]
