# Generated by Django 4.1 on 2022-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0004_alter_timekeeping_fk_doc_reg_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_all',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество часов переработки'),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_paid',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество часов оплачено'),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_received',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Количество часов отгулено'),
        ),
    ]
