# Generated by Django 4.1 on 2022-11-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0005_alter_timekeeping_tk_quantity_hours_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_all',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество часов переработки'),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_paid',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество часов оплачено'),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_received',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество часов отгулено'),
        ),
        migrations.AlterField(
            model_name='timekeeping',
            name='tk_quantity_hours_received_note',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание к отгуленным часам'),
        ),
    ]
