# Generated by Django 4.1 on 2024-02-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0006_alter_timekeeping_tk_quantity_hours_all_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='comp_attestation_status',
            field=models.CharField(choices=[('Присоединен', 'Присоединен'), ('Требует присоединения', 'Требует присоединения'), ('Требует исключения', 'Требует исключения')], max_length=100, verbose_name='Состояние аттестации'),
        ),
    ]
