# Generated by Django 4.1 on 2024-06-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0007_alter_computersisod_comp_attestation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingcryptographicsecurity',
            name='acs_stamp_certificate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отпечаток сертификата'),
        ),
        migrations.AlterField(
            model_name='accountingcryptographicsecurity',
            name='acs_purpose',
            field=models.CharField(blank=True, choices=[('Авторизация ИСОД', 'Авторизация ИСОД'), ('Подпись СЭД', 'Подпись СЭД'), ('Подтверждение личности на интернет порт. "Гос. услуг"', 'Подтверждение личности на интернет порт. "Гос. услуг"'), ('Администратор ГС ПВДНП', 'Администратор ГС ПВДНП'), ('Пользователь ГС ПВДНП', 'Пользователь ГС ПВДНП'), ('Пользователь ГАС ПС', 'Пользователь ГАС ПС')], max_length=100, verbose_name='Назначение'),
        ),
    ]
