# Generated by Django 4.1 on 2024-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0008_accountingcryptographicsecurity_acs_stamp_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingcryptographicsecurity',
            name='acs_serial_number_certificate',
            field=models.CharField(blank=True, max_length=100, verbose_name='Серийный номер сертификата'),
        ),
    ]
