# Generated by Django 4.1 on 2024-06-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0009_accountingcryptographicsecurity_acs_serial_number_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_ic_num',
            field=models.CharField(max_length=50, verbose_name='Номер учета ИЦ'),
        ),
    ]
