# Generated by Django 4.1 on 2024-06-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0010_alter_property_prop_ic_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='prop_ic_num',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер учета ИЦ'),
        ),
    ]
