# Generated by Django 4.1 on 2024-07-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0011_alter_property_prop_ic_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersisod',
            name='comp_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя АРМ, help_text=Формируется из "номер кабинета-ID DST-Рег. номер"'),
        ),
    ]
