# Generated by Django 4.1 on 2024-07-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0012_computersisod_comp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='comp_title',
            field=models.CharField(blank=True, help_text='Формируется из: номер кабинета-ID DST-Рег. номер, например: 3106-I34S13-91', max_length=100, verbose_name='Имя АРМ'),
        ),
    ]
