# Generated by Django 4.1 on 2024-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0013_alter_computersisod_comp_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='comp_attestation_status',
            field=models.CharField(choices=[('Присоединен', 'Присоединен'), ('Требует присоединения', 'Требует присоединения'), ('Требует исключения', 'Требует исключения'), ('Исключен', 'Исключен')], max_length=100, verbose_name='Состояние аттестации'),
        ),
    ]
