# Generated by Django 4.1 on 2024-09-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0014_alter_computersisod_comp_attestation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersisod',
            name='comp_type',
            field=models.CharField(choices=[('Стационарный', 'Стационарный'), ('Мобильный', 'Мобильный')], default='Стационарный', max_length=12, verbose_name='Тип'),
        ),
    ]
