# Generated by Django 4.1 on 2024-09-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0015_computersisod_comp_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersisod',
            name='comp_type_2',
            field=models.CharField(choices=[('Рабочая станция', 'Рабочая станция'), ('Ноутбук', 'Ноутбук')], default='Рабочая станция', max_length=15, verbose_name='Тип АРМ'),
        ),
    ]
