# Generated by Django 4.1 on 2024-09-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0016_computersisod_comp_type_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='comp_type_2',
            field=models.CharField(choices=[('Рабочая станция', 'Рабочая станция'), ('Ноутбук', 'Ноутбук'), ('Моноблок', 'Моноблок'), ('Планшет', 'Планшет')], default='Рабочая станция', max_length=15, verbose_name='Тип АРМ'),
        ),
    ]
