# Generated by Django 4.1 on 2024-09-11 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0017_alter_computersisod_comp_type_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersisod',
            name='fk_admin',
            field=models.ForeignKey(blank=True, db_column='fk_admin', default=84, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ic.employees', verbose_name='Администратор безопасности'),
        ),
    ]
