# Generated by Django 4.1 on 2024-09-11 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0018_computersisod_fk_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='fk_admin',
            field=models.ForeignKey(db_column='fk_admin', default=84, on_delete=django.db.models.deletion.SET_DEFAULT, to='ic.employees', verbose_name='Администратор безопасности'),
        ),
    ]
