# Generated by Django 4.1 on 2024-11-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0019_alter_computersisod_fk_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='computersisod',
            name='comp_os',
            field=models.CharField(choices=[('Windows 10', 'Windows 10'), ('Windows 7', 'Windows 7'), ('Astra Linux', 'Astra Linux'), ('Astra Linux, Windows 10', 'Astra Linux, Windows 10')], default='Windows 10', max_length=100, verbose_name='Операционная система'),
        ),
    ]
