# Generated by Django 4.1 on 2025-04-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0020_computersisod_comp_os'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computersisod',
            options={'ordering': ['comp_attestation_status', 'comp_reg_num', 'comp_ip_address'], 'verbose_name': 'Компьютер сети ИСОД', 'verbose_name_plural': 'Компьютеры сети ИСОД'},
        ),
    ]
