# Generated by Django 4.1 on 2025-04-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0022_alter_computersisod_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diskstorageisod',
            options={'ordering': ['disk_reg_num', 'fk_disk_owner'], 'verbose_name': 'Дисковое хранилище', 'verbose_name_plural': 'Дисковые хранилища'},
        ),
    ]
