# Generated by Django 4.1 on 2025-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ic', '0023_alter_diskstorageisod_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computersisod',
            name='comp_reg_num',
            field=models.IntegerField(help_text='Данный номер наклен на системный блок ПК сети ИСОД', unique=True, verbose_name='Рег. номер'),
        ),
    ]
